### ISSUE TITLE
官方的视频sdk在树莓派下根本不能编译成功

### ISSUE THREAD

**Issue by jiayaoO3O** [cm-heclouds/video_sdk#2]
官方sdk在正常的Ubuntu64位系统下可以直接编译成功,但是在树莓派上完全不可以,太多坑了
      1.这个问题上一个提问的lssues已经提到了,提示/uer/bin/ld:找不到-lssl和-lcrypto,这个问题可以通过sudo
apt-get install libssl-dev来解决.
      2.第二个问题是libmbedcrypeo.a:无法添加符号:不可识别的文件格式,这个也需要自己编译mbedtls,但是具体怎么编译,编译了之后文件放哪,也没讲清楚.
      3.更惨的是上面两个问题解决之后,openssl库一直出问题
![_20181104210932](https://user-images.githubusercontent.com/22891632/47964779-8281a800-e079-11e8-8f63-472414b854b7.png)
一直报这个对openssl函数库里的未定义的引用,希望官方能够尽快修复漏洞,并且更新更加适合新手的参考文档,谢谢

**Comment by guapiguapi** [comment]
我试过了，你需要自己编译openssl1.0.2，但是我在编译成功后出现Segmentation fault的错误

**Comment by jiayaoO3O** [comment]
我已经成功编译出文件了，很久以前了，参考了很多文章才成功的，并没有教程说的这么简单，你需要的话我可以把文件发给你

**Comment by guapiguapi** [comment]
请问您能成功将实时视频推送到onenet平台吗？我在编译成功后运行时出现Segmentation fault的错误，并不能推送实时视频。

**Comment by jiayaoO3O** [comment]
可以直接使用,文件[点击下载](https://c-t.work/s/265058a1391942),只有72小时.

**Comment by wuji20143028** [comment]
您好，我这里编译成功之后可以推流本地视频，但推流摄像头采集的实时视频时也出现了segmentation fault错误，想问一下你编译成功后会出现这个问题吗？谢谢

**Comment by guapiguapi** [comment]
> 您好，我这里编译成功之后可以推流本地视频，但推流摄像头采集的实时视频时也出现了segmentation fault错误，想问一下你编译成功后会出现这个问题吗？谢谢

我暂时没有继续做这个，但是楼主提供了一个编译好的例子链接：https://pan.baidu.com/s/1JcEM4ze4YnGIEGTW5B6nYg 
提取码：0ani 
但是我还没有尝试，你可以试一下

**Comment by wuji20143028** [comment]
> > 您好，我这里编译成功之后可以推流本地视频，但推流摄像头采集的实时视频时也出现了segmentation fault错误，想问一下你编译成功后会出现这个问题吗？谢谢
> 
> 我暂时没有继续做这个，但是楼主提供了一个编译好的例子链接：https://pan.baidu.com/s/1JcEM4ze4YnGIEGTW5B6nYg
> 提取码：0ani
> 但是我还没有尝试，你可以试一下

你好，谢谢提供的文件，但是我试过之后发现推流在线视频时，依然会出现segmentation fault
